-----------------------------
--BASE DE DATOS RESTAURANTE--
-----------------------------
--Borrar tablas--
DROP TABLE ADMINISTRADOR;
DROP TABLE RESTAURANTE;
DROP TABLE ESTABLECIMIENTOS;
DROP TABLE PERSONAL;
DROP TABLE CARGO;
DROP TABLE CLIENTES_CAJA;
DROP TABLE CAJA;
DROP TABLE CLIENTES;
DROP TABLE PEDIDOS_VENTA;
DROP TABLE VENTA_PLATOS;
DROP TABLE RECETA;
DROP TABLE PLATOS;
DROP TABLE CARTA;
DROP TABLE TIPO_MENU;


--Creacion de tablas--
CREATE TABLE TIPO_MENU(
    COD_TIPO_MENU NUMBER(4) PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    PRECIO NUMBER(3)
);
CREATE TABLE CARTA(
    COD_CARTA NUMBER(4) PRIMARY KEY,
    DESCRIPCION VARCHAR2(100)
);
CREATE TABLE PLATOS(
    COD_PLATOS NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(32),
    DESCRIPCION VARCHAR2(100),
    PRECIO NUMBER(3),
    COD_CARTA NUMBER(4) REFERENCES CARTA(COD_CARTA),
    COD_TIPO_MENU NUMBER(4) REFERENCES TIPO_MENU(COD_TIPO_MENU)
);
CREATE TABLE RECETA(
    COD_RECETA NUMBER(4) PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    COD_PLATOS NUMBER(4) REFERENCES PLATOS(COD_PLATOS)
);
CREATE TABLE VENTA_PLATOS(
    COD_VENTA_PLATOS NUMBER(4) PRIMARY KEY,
    FECHA DATE,
    TIPO_PAGO VARCHAR2(20),
    COD_PLATOS NUMBER(4) REFERENCES PLATOS(COD_PLATOS),
    CONSTRAINT CAJ_TIP_CH CHECK (TIPO_PAGO IN ('Metalico', 'Tarjeta', 'Bizum'))
);
CREATE TABLE PEDIDOS_VENTA(
    COD_PEDIDOS_VENTA NUMBER(4) PRIMARY KEY,
    FECHA DATE,
    COD_VENTA_PLATOS NUMBER(4) REFERENCES VENTA_PLATOS(COD_VENTA_PLATOS)
);
CREATE TABLE CLIENTES(
    COD_CLIENTES NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(32),
    PRIMER_APELLIDO VARCHAR2(32),
    SEGUNDO_APELLIDO VARCHAR2(32),
    DIRECCION VARCHAR2(45),
    TELEFONO NUMBER(9),
    TIPO_PAGO VARCHAR2(20),
    COD_PEDIDOS_VENTA NUMBER(4) REFERENCES PEDIDOS_VENTA(COD_PEDIDOS_VENTA),
    CONSTRAINT CLI_TIP_CH CHECK (TIPO_PAGO IN ('Metalico', 'Tarjeta', 'Bizum'))
);
CREATE TABLE CAJA(
    COD_CAJA NUMBER(4) PRIMARY KEY,
    NOMBRE_PLATO VARCHAR2(32),
    PRECIO NUMBER(3),
    TIPO_PAGO VARCHAR2(20),
    CONSTRAINT CAJA_TIP_CH CHECK (TIPO_PAGO IN ('Metalico', 'Tarjeta', 'Bizum'))
);
CREATE TABLE CLIENTES_CAJA(
    CODIGO NUMBER(4) PRIMARY KEY,
    COD_CLIENTES NUMBER(4),
    COD_CAJA NUMBER(4),
    CONSTRAINT CLI_CODCL_FK FOREIGN KEY (COD_CLIENTES) REFERENCES CLIENTES(COD_CLIENTES),
    CONSTRAINT CLI_CODCA_FK FOREIGN KEY (COD_CAJA) REFERENCES CAJA(COD_CAJA)
); 
CREATE TABLE CARGO(
    COD_CARGO NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(32),
    DESCRIPCION VARCHAR2(100)
);
CREATE TABLE PERSONAL(
    COD_PERSONAL NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(32),
    PRIMER_APELLIDO VARCHAR2(32),
    SEGUNDO_APELLIDO VARCHAR2(32),
    SUELDO NUMBER(4),
    TURNO VARCHAR2(32),
    COD_CARGO NUMBER(4) REFERENCES CARGO(COD_CARGO),
    CONSTRAINT PER_TUR_CH CHECK (TURNO IN ('Mañana', 'Tarde'))
);
CREATE TABLE ESTABLECIMIENTOS(
    COD_ESTABLECIMIENTO NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(32),
    TELEFONO NUMBER(9),
    CODIGO_POSTAL NUMBER(5),
    CATEGORIA VARCHAR2(50)
);
CREATE TABLE RESTAURANTE(
    COD_RESTAURANTE NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(32),
    DIRECCION VARCHAR2(45),
    TELEFONO NUMBER(9),
    COD_ESTABLECIMIENTO NUMBER(4) REFERENCES ESTABLECIMIENTOS(COD_ESTABLECIMIENTO)
);
CREATE TABLE ADMINISTRADOR(
    COD_ADMINISTRADOR NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(32),
    PRIMER_APELLIDO VARCHAR2(32),
    SEGUNDO_APELLIDO VARCHAR2(32),
    DIRECCION VARCHAR2(45),
    TELEFONO NUMBER(9),
    COD_RESTAURANTE NUMBER(4) REFERENCES RESTAURANTE(COD_RESTAURANTE),
    COD_PERSONAL NUMBER(4) REFERENCES PERSONAL (COD_PERSONAL)
);


--Insertar datos en las tablas--
INSERT INTO TIPO_MENU (COD_TIPO_MENU, DESCRIPCION, PRECIO) VALUES(1, 'Menu China: Va con rollito de primavera', 10);
INSERT INTO TIPO_MENU (COD_TIPO_MENU, DESCRIPCION, PRECIO) VALUES(2, 'Menu America: La hamburguesa es 100% Vacuno', 10);
INSERT INTO TIPO_MENU (COD_TIPO_MENU, DESCRIPCION, PRECIO) VALUES(3, 'Menu EspaÃ±a: La paella que jamas hayas probado', 15);
INSERT INTO TIPO_MENU (COD_TIPO_MENU, DESCRIPCION, PRECIO) VALUES(4, 'Menu Francia: Le acompaÃ±a el mejor pan brioche', 15);
INSERT INTO TIPO_MENU (COD_TIPO_MENU, DESCRIPCION, PRECIO) VALUES(5, 'Menu Portugal: un rico bacalao a la Gomes de Sa', 15);
--SELECT * FROM TIPO_MENU;--

INSERT INTO CARTA(COD_CARTA, DESCRIPCION) VALUES(1, 'Bebida');
INSERT INTO CARTA(COD_CARTA, DESCRIPCION) VALUES(2, 'Entrante');
INSERT INTO CARTA(COD_CARTA, DESCRIPCION) VALUES(3, 'Carne');
INSERT INTO CARTA(COD_CARTA, DESCRIPCION) VALUES(4, 'Pescado');
INSERT INTO CARTA(COD_CARTA, DESCRIPCION) VALUES(5, 'Postre');
--SELECT * FROM CARTA;--

INSERT INTO PLATOS(COD_PLATOS, NOMBRE, DESCRIPCION, PRECIO, COD_CARTA, COD_TIPO_MENU) VALUES(1, 'Ensaladilla', 'Ensalada de papa, gisantes y huevos cocido mezclado con mayonesa', 4, 2, 3);
INSERT INTO PLATOS(COD_PLATOS, NOMBRE, DESCRIPCION, PRECIO, COD_CARTA, COD_TIPO_MENU) VALUES(2, 'Pulpo a la gallega', 'Es un pulpo cocido con patatas hervidas y se mezcla con especias', 8, 4, 3);
INSERT INTO PLATOS(COD_PLATOS, NOMBRE, DESCRIPCION, PRECIO, COD_CARTA, COD_TIPO_MENU) VALUES(3, 'Ternera altiavel', 'Ternera al la plancha con salsa especiales de la casa', 9, 3, 1);
INSERT INTO PLATOS(COD_PLATOS, NOMBRE, DESCRIPCION, PRECIO, COD_CARTA, COD_TIPO_MENU) VALUES(4, 'Costillar', 'Es una costilla a la barbacoa con salsa BBQ', 15, 3, 2);
INSERT INTO PLATOS(COD_PLATOS, NOMBRE, DESCRIPCION, PRECIO, COD_CARTA, COD_TIPO_MENU) VALUES(5, 'macarron de sabores', 'Galleta hecha con clara de huevo y almendra', 7, 5, 4);
--SELECT * FROM PLATOS;--

INSERT INTO RECETA(COD_RECETA, DESCRIPCION, COD_PLATOS) VALUES(1, 'papa, huevo y Mayonesa todo mezclado', 1);
INSERT INTO RECETA(COD_RECETA, DESCRIPCION, COD_PLATOS) VALUES(2, 'Se cuece el pulpo, hierve la patata y se zasona en especias', 2);
INSERT INTO RECETA(COD_RECETA, DESCRIPCION, COD_PLATOS) VALUES(3, 'Ternera a la plancha y se le pone la salsa', 3);
INSERT INTO RECETA(COD_RECETA, DESCRIPCION, COD_PLATOS) VALUES(4, 'Se asa a la barbaco la costilla y se le aÃ±ade la salsa BBQ', 4);
INSERT INTO RECETA(COD_RECETA, DESCRIPCION, COD_PLATOS) VALUES(5, 'Se monta el macarron y se hornea', 5);
--SELECT * FROM RECETA;--

INSERT INTO VENTA_PLATOS(COD_VENTA_PLATOS, FECHA, TIPO_PAGO, COD_PLATOS) VALUES(1, '14/05/2022', 'Metalico', 2);
INSERT INTO VENTA_PLATOS(COD_VENTA_PLATOS, FECHA, TIPO_PAGO, COD_PLATOS) VALUES(2, '25/06/2021', 'Tarjeta', 3);
INSERT INTO VENTA_PLATOS(COD_VENTA_PLATOS, FECHA, TIPO_PAGO, COD_PLATOS) VALUES(3, '01/03/2022', 'Metalico', 2);
INSERT INTO VENTA_PLATOS(COD_VENTA_PLATOS, FECHA, TIPO_PAGO, COD_PLATOS) VALUES(4, '05/03/2022', 'Bizum', 4);
INSERT INTO VENTA_PLATOS(COD_VENTA_PLATOS, FECHA, TIPO_PAGO, COD_PLATOS) VALUES(5, '25/04/2022', 'Metalico', 5);
--SELECT * FROM VENTA_PLATOS;--

INSERT INTO PEDIDOS_VENTA(COD_PEDIDOS_VENTA, FECHA, COD_VENTA_PLATOS) VALUES(1, '14/05/2022', 2);
INSERT INTO PEDIDOS_VENTA(COD_PEDIDOS_VENTA, FECHA, COD_VENTA_PLATOS) VALUES(2, '25/06/2021', 3);
INSERT INTO PEDIDOS_VENTA(COD_PEDIDOS_VENTA, FECHA, COD_VENTA_PLATOS) VALUES(3, '01/03/2022', 2);
INSERT INTO PEDIDOS_VENTA(COD_PEDIDOS_VENTA, FECHA, COD_VENTA_PLATOS) VALUES(4, '05/03/2022', 4);
INSERT INTO PEDIDOS_VENTA(COD_PEDIDOS_VENTA, FECHA, COD_VENTA_PLATOS) VALUES(5, '25/04/2022', 5);
--SELECT * FROM PEDIDOS_VENTA;--

INSERT INTO CLIENTES(COD_CLIENTES, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, TIPO_PAGO, COD_PEDIDOS_VENTA) VALUES(1, 'Ruben', 'Torres', 'Lopez', 'Calle Arrabal n68', 654897231, 'Metalico', 1);
INSERT INTO CLIENTES(COD_CLIENTES, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, TIPO_PAGO, COD_PEDIDOS_VENTA) VALUES(2, 'Angela', 'Chamoro', 'Castro', 'Calle BuenOjete n69', 633859745, 'Tarjeta', 2);
INSERT INTO CLIENTES(COD_CLIENTES, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, TIPO_PAGO, COD_PEDIDOS_VENTA) VALUES(3, 'Raquel', 'Villanueva', 'Portillo', 'Calle Almeta n33', 695847123, 'Metalico', 3);
INSERT INTO CLIENTES(COD_CLIENTES, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, TIPO_PAGO, COD_PEDIDOS_VENTA) VALUES(4, 'Carlos', 'Calcamon', 'Gonzalez', 'Calle Camino Sierra n56', 625487952, 'Bizum', 4);
INSERT INTO CLIENTES(COD_CLIENTES, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, TIPO_PAGO, COD_PEDIDOS_VENTA) VALUES(5, 'Noelia', 'Morato', 'Gallego', 'Calle Corredera n57B', 635412898, 'Metalico', 5);
--SELECT * FROM CLIENTES;--

INSERT INTO CAJA(COD_CAJA, NOMBRE_PLATO, PRECIO, TIPO_PAGO) VALUES (1, 'Pulpo a la gallega', 8, 'Metalico');
INSERT INTO CAJA(COD_CAJA, NOMBRE_PLATO, PRECIO, TIPO_PAGO) VALUES (2, 'Ternera altiavel', 9, 'Tarjeta');
INSERT INTO CAJA(COD_CAJA, NOMBRE_PLATO, PRECIO, TIPO_PAGO) VALUES (3, 'Pulpo a la gallega', 8, 'Metalico');
INSERT INTO CAJA(COD_CAJA, NOMBRE_PLATO, PRECIO, TIPO_PAGO) VALUES (4, 'Costillar', 15, 'Bizum');
INSERT INTO CAJA(COD_CAJA, NOMBRE_PLATO, PRECIO, TIPO_PAGO) VALUES (5, 'Macarron de sabores', 7, 'Metalico');
--SELECT * FROM CAJA;--

INSERT INTO CLIENTES_CAJA(CODIGO, COD_CLIENTES, COD_CAJA) VALUES(1, 1, 1);
INSERT INTO CLIENTES_CAJA(CODIGO, COD_CLIENTES, COD_CAJA) VALUES(2, 2, 2);
INSERT INTO CLIENTES_CAJA(CODIGO, COD_CLIENTES, COD_CAJA) VALUES(3, 3, 3);
INSERT INTO CLIENTES_CAJA(CODIGO, COD_CLIENTES, COD_CAJA) VALUES(4, 4, 4);
INSERT INTO CLIENTES_CAJA(CODIGO, COD_CLIENTES, COD_CAJA) VALUES(5, 5, 5);
--SELECT * FROM CLIENTES_CAJA;--

INSERT INTO CARGO(COD_CARGO, NOMBRE, DESCRIPCION) VALUES(1, 'Jefe de sala', '');
INSERT INTO CARGO(COD_CARGO, NOMBRE, DESCRIPCION) VALUES(2, 'Camarero', '');
INSERT INTO CARGO(COD_CARGO, NOMBRE, DESCRIPCION) VALUES(3, 'Cocinero', '');
INSERT INTO CARGO(COD_CARGO, NOMBRE, DESCRIPCION) VALUES(4, 'Limpiadores', '');
--SELECT * FROM CARGO;--

INSERT INTO PERSONAL(COD_PERSONAL, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, SUELDO, TURNO, COD_CARGO) VALUES(1, 'Enrrique', 'Garcia', 'Bustos', 1800, 'Mañana', 1);
INSERT INTO PERSONAL(COD_PERSONAL, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, SUELDO, TURNO, COD_CARGO) VALUES(2, 'Laura', 'Pastor', 'Velez', 1200, 'Mañana', 3);
INSERT INTO PERSONAL(COD_PERSONAL, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, SUELDO, TURNO, COD_CARGO) VALUES(3, 'Antonio', 'Moreno', 'Casado', 1200, 'Tarde', 2);
INSERT INTO PERSONAL(COD_PERSONAL, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, SUELDO, TURNO, COD_CARGO) VALUES(4, 'Pepe', 'Montes', 'Calvo', 1200, 'Mañana', 2);
INSERT INTO PERSONAL(COD_PERSONAL, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, SUELDO, TURNO, COD_CARGO) VALUES(5, 'David', 'Zambrano', 'Bustos', 800, 'Mañana', 4);
--SELECT * FROM PERSONAL;--

INSERT INTO ESTABLECIMIENTOS(COD_ESTABLECIMIENTO, NOMBRE, TELEFONO, CODIGO_POSTAL, CATEGORIA) VALUES(1, 'Casa Moreno-Lora del Rio', 654857496, 41440, '3 Estrella Michelin');
INSERT INTO ESTABLECIMIENTOS(COD_ESTABLECIMIENTO, NOMBRE, TELEFONO, CODIGO_POSTAL, CATEGORIA) VALUES(2, 'Casa Moreno-Mairena del alcor', 654857497, 41510, '2 Estrella Michelin');
INSERT INTO ESTABLECIMIENTOS(COD_ESTABLECIMIENTO, NOMBRE, TELEFONO, CODIGO_POSTAL, CATEGORIA) VALUES(3, 'Casa Moreno-Bellavista',654857498, 41514, '0 Estrella Michelin' );
--SELECT * FROM ESTABLECIMIENTOS;--

INSERT INTO RESTAURANTE(COD_RESTAURANTE, NOMBRE, DIRECCION, TELEFONO, COD_ESTABLECIMIENTO) VALUES(1, 'Casa Moreno-Lora del rio', 'Lora del Rio n7', 654857496, 1);
INSERT INTO RESTAURANTE(COD_RESTAURANTE, NOMBRE, DIRECCION, TELEFONO, COD_ESTABLECIMIENTO) VALUES(2, 'casa Moreno-Mairena del alcor', 'Mairena del alcor n7', 654857497, 2);
INSERT INTO RESTAURANTE(COD_RESTAURANTE, NOMBRE, DIRECCION, TELEFONO, COD_ESTABLECIMIENTO) VALUES(3, 'Casa Moreno-Bellavista', 'Bellavista n7', 654857498, 3);
--SELECT * FROM RESTAURANTE;--

INSERT INTO ADMINISTRADOR(COD_ADMINISTRADOR, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, COD_RESTAURANTE, COD_PERSONAL) VALUES(1, 'Enrrique', 'Garcia', 'Bustos', 'Calle Balmes n7',652100230, 1, 1);
INSERT INTO ADMINISTRADOR(COD_ADMINISTRADOR, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, COD_RESTAURANTE, COD_PERSONAL) VALUES(2, 'Enrrique', 'Garcia', 'Bustos', 'Calle Balmes n7',652100230, 2, 1);
INSERT INTO ADMINISTRADOR(COD_ADMINISTRADOR, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, TELEFONO, COD_RESTAURANTE, COD_PERSONAL) VALUES(3, 'Enrrique', 'Garcia', 'Bustos', 'Calle Balmes n7',652100230, 3, 1);
--SELECT * FROM ADMINISTRADOR;--