Set serveroutput on;

--Funcion que modifica el turno de un personal-- REVISAR HAY ALGO QUE FALLA
CREATE OR REPLACE FUNCTION MODIFICAR_TURNO(
    V_COD_PERSONAL personal.cod_personal%type,
    TURNO_NUEVO personal.turno%type)
    RETURN BOOLEAN
AS
BEGIN
    UPDATE PERSONAL SET TURNO=TURNO_NUEVO WHERE COD_PERSONAL=V_COD_PERSONAL;
    DBMS_OUTPUT.PUT_LINE('Se ha actualizado el turno correctamente.');
    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ha habido un erro!');
    RETURN FALSE;
END;
/
SELECT * FROM PERSONAL;
SELECT MODIFICAR_TURNO(1, 'Tarde') FROM DUAL;
--Funcion que cuenta los clientes que ha habido hasta ahora en los restaurantes-- BIEN Y FUNCIONA
CREATE OR REPLACE FUNCTION CUENTA_CLIENTES
RETURN NUMBER
AS
    CUENTA_CLIENTE NUMBER(4);
BEGIN
    SELECT COUNT(NOMBRE) INTO CUENTA_CLIENTE FROM CLIENTES;
    RETURN CUENTA_CLIENTE;
END;
/


--Procedimiento que inserta datos en la tabla TIPO_MENU-- BIEN Y FUNCIONA
CREATE OR REPLACE PROCEDURE INSERTA_TIPO_MENU (
  V_COD_TIPO_MENU	TIPO_MENU.COD_TIPO_MENU%TYPE, 
  V_DESCRIPCION	TIPO_MENU.DESCRIPCION%TYPE,
  V_PRECIO		TIPO_MENU.PRECIO%TYPE)
IS
BEGIN
  INSERT INTO TIPO_MENU (COD_TIPO_MENU, DESCRIPCION, PRECIO)
    VALUES (V_COD_TIPO_MENU, V_DESCRIPCION, V_PRECIO);
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('Uno de los campos esta mal introducido.');
END INSERTA_TIPO_MENU;
/


--Procedimiento para borrar datos en la tabla TIPO_MENU-- BIEN Y FUNCIONA
CREATE OR REPLACE PROCEDURE BORRAR_TIPO_MENU (
  V_COD_TIPO_MENU	TIPO_MENU.COD_TIPO_MENU%TYPE) 
AS
BEGIN
    DELETE FROM TIPO_MENU WHERE COD_TIPO_MENU = V_COD_TIPO_MENU;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('No existe el codigo '||V_COD_TIPO_MENU);
END BORRAR_TIPO_MENU;
/


--Cursores para operar con la base de datos Restaurante--
DECLARE
MOSTRAR_PERSONAL PERSONAL%ROWTYPE;
BEGIN
SELECT * INTO MOSTRAR_PERSONAL FROM PERSONAL;
DBMS_OUTPUT.PUT_LINE('COD_PERSONAL: '||MOSTRAR_PERSONAL.COD_PERSONAL);
DBMS_OUTPUT.PUT_LINE('NOMBRE: '||MOSTRAR_PERSONAL.NOMBRE);
END;
/

--bloque Anonimo que actua como main-- REVISAR Y CORREGIR
DECLARE
    DECISION NUMBER(2);
    COD NUMBER(4);
    DESCRIP VARCHAR(100);
    PRECIO NUMBER(3);
    TURNO_NUEVO VARCHAR2(32);
    N_CLIENTES NUMBER(4);
    bol BOOLEAN;
BEGIN
    DBMS_OUTPUT.PUT_LINE('¿Que quieres hacer?');
    DBMS_OUTPUT.PUT_LINE('1. Insertar Datos en la tabla.');
    DBMS_OUTPUT.PUT_LINE('2. Borrar Datos de la tabla.');
    DBMS_OUTPUT.PUT_LINE('3. Modificar Datos de la tabla.');
    DBMS_OUTPUT.PUT_LINE('4. Contar cuantos clientes no han visitado ya.');
    DECISION := '&DEC1';

    IF DECISION = 1
        COD := '&COD1';
        DESCRIP := '&DES1';
        PRECIO := '&PRE1';
        EXEC INSERTA_TIPO_MENU(COD, DESCRIP, PRECIO);
    ELSIF DECISION = 2   
        COD := '&COD1';
        EXEC BORRAR_TIPO_MENU(COD);
    ELSIF DECISION = 3  
        COD := '&COD1';
        TURNO_NUEVO := '&TUR1';
        bol := MODIFICAR_TURNO(COD, TURNO_NUEVO);
        
    ELSE
        N_CLIENTE := SELECT CUENTA_CLIENTES FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('Los clientes que hay son: '||N_CLIENTE);
    END IF;
    
END;
/

